AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Visitor Counter for Cloud Resume Challenge

Resources:
  VisitorCountTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: VisitorCountNew
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  UpdateVisitorCountFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: updateVisitorCountNew
      Handler: app.lambda_handler
      Runtime: python3.9
      CodeUri: ./lambda_function
      Policies:
        - DynamoDBCrudPolicy:
            TableName: VisitorCountNew
      Environment:
        Variables:
          TABLE_NAME: VisitorCountNew
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref VisitorCounterApi  # Explicitly reference the API
            Path: /count
            Method: GET

  VisitorCounterApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowOrigin: "'https://sirghevladaws.com'"
        AllowMethods: "'GET,OPTIONS'"
        AllowHeaders: "'Content-Type'"

Outputs:
  ApiUrl:
    Description: URL for the API Gateway endpoint
    Value: !Sub "https://${VisitorCounterApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/count"


