version = 0.1
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::243547532538:user/IAMadmin"
permissions_provider = "AWS IAM"

[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::243547532538:role/aws-sam-cli-managed-dev-pipel-PipelineExecutionRole-ancxAT1a4efW"
cloudformation_execution_role = "arn:aws:iam::243547532538:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionRo-xMoztYyfRS3i"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-r-artifactsbucket-chbfgr8hs5ox"
image_repository = ""
region = "us-east-1"

[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::243547532538:role/aws-sam-cli-managed-prod-pipe-PipelineExecutionRole-OjZWT7GGFuhN"
cloudformation_execution_role = "arn:aws:iam::243547532538:role/aws-sam-cli-managed-prod--CloudFormationExecutionRo-jH2LRipDYjV3"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline--artifactsbucket-p4zp6swo9njz"
image_repository = ""
region = "us-east-1"
